### ISSUE TITLE
A Question about how Midi Rhythm Trainer works

### ISSUE THREAD

**Issue by 11Retsof** [erangithub/reaper_jsfx#3]
Hello, this isn't an issue but I couldn't find how to contact you Eran about this plugin. I'm interested in a way of analyzing rhythmic information from midi files (could be single channel, doesn't have to be multiples as I could combine information later). I'm not sure from your videos whether your plugin just works with live midi information or if it would work with an already recorded midi file.  I have a very large number of midi files from a project back in the 90s that I'm trying to analyse for research into 16th note incidence in specific world musics, and oddly just don't seem to be able to find anything that does what your plugin seems to do (much of it is even split into right and left hand as you show in your video, just not live!). I don't have Reaper but given how many months of work this could save me I certainly don't mind buying it! Kind regards, Foster

**Comment by erangithub** [comment]
Hi Foster, 
you can apply the midi rhythm trainer to pre-recorded midi, but you will have to let the Reaper play it out.
Of course, you may speed up the tempo to save time, and it should produce the same analysis.
If you have further questions feel free to contact me at eran_talmorg@yahoo.com
--Eran
