### ISSUE TITLE
My Lanes 2, 3, and 4 don't have MIDI signals.

### ISSUE THREAD

**Issue by guitarspace** [erangithub/reaper_jsfx#6]
My Lanes 2, 3, and 4 don't have MIDI signals.
Do I need to make any settings?
<img width="1689" alt="CleanShot 2023-08-09 at 01 38 27@2x" src="https://github.com/erangithub/eran_reaper_jsfx/assets/33551916/6cf4a4fe-6f03-4f8b-93bc-0ef886d381e4">

**Comment by erangithub** [comment]
Any midi data that is captured by the first lane, won't go to the next lane, etc..
By default, the first lane will catch all of the midi data on all channels, and all notes (C0 -> G10).
If you want some of the data to pass to the other lanes, you need to either set lane 1 to just listen to (e.g.) CH1, lane 2 to CH2,...
Or set different key ranges in the lanes ... so C5->G10 in lane 1, will let notes below C5 fall through to the next lanes.

Hope this helps
Eran

**Comment by guitarspace** [comment]
It worked! Thank you so much for developing this program. It has been immensely helpful for my guitar practice.
I have two feature requests. I'm wondering if they can be implemented.

1.If it's possible to add something like a checkbox symbol on each Division, allowing users to click on it, and then it becomes a solid square, serving as the rhythm's 'target' or 'basket,' it would provide a clear visual goal for rhythm practice. I currently use screen drawing to manually draw targets on the MIDI Rhythm Trainer, and the results I've achieved in teaching have been quite good, so I'm suggesting this feature.

 
<img width="997" alt="CleanShot 2023-08-07 at 23 02 28@2x" src="https://github.com/erangithub/eran_reaper_jsfx/assets/33551916/d2437d27-d73e-4ec1-ae2e-10b6b5bee7dd">

2.Is it possible to display the full error boundary for the first beat?
Because I can only see the right half, there's a sense of uncertainty regarding the timing of the first beat. I use the Phase to shift the bar to the right, but then I need to compensate for errors based on different speeds and the value of the Error Bound.

![CleanShot 2023-08-09 at 22 45 25@2x](https://github.com/erangithub/eran_reaper_jsfx/assets/33551916/1e5dbcd0-2e55-4cc9-927b-84cebc2d15ec)


（Translated through ChatGPT）

**Comment by erangithub** [comment]
For your first question - this already exists: you can toggle specific grid lines on/off by simply right clicking them.
Regarding the second question - the other half lf the firsy grid line is on the other side of the grid... Of the right. But i csn see how this can be improved by adding some margins. Ill consider it for a future feature

**Comment by erangithub** [comment]
For the "target basket" - do check my tutorial video at 8:35 seconds:  https://youtu.be/cifj6eh_LF0?t=515.

**Comment by guitarspace** [comment]
> For the "target basket" - do check my tutorial video at 8:35 seconds: https://youtu.be/cifj6eh_LF0?t=515.

This information is very helpful, thank you.

**Comment by erangithub** [comment]
I updated another version 1.22 with some cool improvements that should address your questions. Check it out
![mrt1 22](https://github.com/erangithub/eran_reaper_jsfx/assets/28439804/432e7961-27ab-4a87-9c34-77fe4e35c6ff)

**Comment by guitarspace** [comment]
I am once again excited and eager to use the new version. The "beat ruler with alternating colors" and "Added margins on the left and right of the grid" features are fantastic. After using them for a few hours, I can distinctly feel that the accuracy of the first beat has significantly improved. Especially being able to see the visual effect of "preparation leading up to the first beat" makes beats feel more natural. I did notice a minor bug, where the color determination for the first beat on the far left and far right is out of sync.
![CleanShot 2023-08-12 at 09 29 22@2x](https://github.com/erangithub/eran_reaper_jsfx/assets/33551916/d1ca8af3-b7f5-47a5-88ea-6fe2ac830368)

![CleanShot 2023-08-12 at 09 30 25@2x](https://github.com/erangithub/eran_reaper_jsfx/assets/33551916/48a6568b-ca3e-4360-9dc9-66bb4d3a9ad1)

**Comment by erangithub** [comment]
Im very glad that you like it. The color mismatch thing is intentional: these grey circles are duplicate "shadow" events on the margins. In other words if you see something gray you know duplicates another event that is within the grid.

**Comment by guitarspace** [comment]
Now I understand the logic behind the gray function, thank you.
I'm very grateful that you've implemented several features I've suggested. I have another feature request. I hope there's a way to change the color of the selected error bound using, for instance, "ctrl + left mouse click", to a different color (like yellow). Clicking again would revert it back to the original green color. The reason I want this feature is somewhat similar to the previous basket concept (use right mouse click), but it's slightly different. For instance, I might want to emphasize the 1st, 4th, and 7th positions out of 8 beats, but I would still play all 8 positions. Thus, I don't want the 2nd, 3rd, 5th, 6th, and 8th positions to disappear; I just want to "highlight" these three positions with a different color.
Can you work your magic again.

**Comment by guitarspace** [comment]
Is it possible to add a feature to switch the color of the selected rectangle by pressing ctrl + left mouse click? (For example, toggling between the original green and yellow). I know this can enhance practice efficiency. I've been using screen drawing tools to achieve this effect (to highlight the emphasis notes), and I've received significant positive feedback from students in my teaching. I've tried to look into the source code to implement this feature myself. However, after dozens of hours of effort, I must admit my coding abilities are lacking. So, I'm asking for your help to develop this feature. Please assist.
![CleanShot 2023-08-18 at 01 27 53@2x](https://github.com/erangithub/eran_reaper_jsfx/assets/33551916/d2addc2f-d6fc-4f5d-a19c-22802ce0abe1)

**Comment by erangithub** [comment]
Please open a separate issue - so I can close this one.
Thanks


> Is it possible to add a feature to switch the color of the selected rectangle by pressing ctrl + left mouse click? (For example, toggling between the original green and yellow). I know this can enhance practice efficiency. I've been using screen drawing tools to achieve this effect (to highlight the emphasis notes), and I've received significant positive feedback from students in my teaching. I've tried to look into the source code to implement this feature myself. However, after dozens of hours of effort, I must admit my coding abilities are lacking. So, I'm asking for your help to develop this feature. Please assist. ![CleanShot 2023-08-18 at 01 27 53@2x](https://user-images.githubusercontent.com/33551916/261389540-d2addc2f-d6fc-4f5d-a19c-22802ce0abe1.png)
